### ISSUE TITLE
Strange characters in OS X

### ISSUE THREAD

**Issue by faceleg** [willghatch/zsh-megaprompt#1]
I'm experiencing an odd visual issue in OS X:

```
22:31 [vagrant@vagrant-ubuntu-trusty-64] [01;31m* master D U] ~/
? 19 λ
```

The issue here is the `01;31m*` portion.

What could be causing this? 

What can I provide to you to help debug this issue?

I'm using iTerm2, zsh 5.0.8 (x86_64-apple-darwin14.3.0), tmux.

**Comment by willghatch** [comment]
Hmm, it could be a problem with the -mp-styleBranch function.  What `MEGAPROMPT_GIT_STYLES` have you set?  Or more specifically, what have you set for master?  The default is `%b%F{white}`, which should end up sending `\e[0;37m` there, which is not what you're getting, so I'm wondering if your setting is acting weird.  Also, the `*` should have been stripped by -mp-getGitBranch slicing off the first two characters.  I'm not sure what could be causing that.  Do you have some setting that makes `git branch` output anything different than normal?

**Comment by faceleg** [comment]
I'm running the megaprompt with no customizations

**Comment by willghatch** [comment]
Hmm.  I don't own a Mac, so I don't really have an easy way to test it.  But I have friends that have Macs, so the next time I'm with them I'll see if I can do some quick debugging.

**Comment by willghatch** [comment]
So I roped a Mac user at a workshop I've been at this week into looking at it with me for a minutes.  The problem is differences between GNU and BSD utilities (sed, etc).  I'll spin up a FreeBSD virtual machine some time (maybe next week) and see if I can find all the offenders and fix them.

**Comment by faceleg** [comment]
Thanks for the update!

**Comment by willghatch** [comment]
Ok, I've set up a BSD virtual machine, and I've fixed all the bugs I see on it.  However, I never saw weird characters either when I looked at it with the guy at the workshop or on this BSD installation.  So let me know if the issue is fixed or is still there.

Also note that I added a horizontal rule line to the default config, so you will notice that now as well.

**Comment by faceleg** [comment]
Thanks!
