### ISSUE TITLE
grep: conflicting matchers specified

### ISSUE THREAD

**Issue by hawko2600** [willghatch/zsh-megaprompt#3]
the precmd hook causes this error; on lines 84 & 85 and 165 & 166 the invocation of 'grep' should be 'command grep' as it is assuming the user hasn't aliased grep to something else.

In my case, I always want posix extended so I have grep aliased to 'grep -E' and this conflicted with lines 84 & 85 in particular.  An alternative would be to use 'fgrep' instead of 'grep -F' in these lines, as is done in line 136.

**Comment by willghatch** [comment]
Thanks.  I generally try not to alias over common command names, so I don't run into such issues.
